mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "root&1234"
  db: "uima"
  charset: "UTF-8"
token:
  secret_key: "generating_secrect_key_by_EF"
web:
  host: "119.3.2.168"
  port: 8795
