// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terrms",
        "contact": {
            "name": "Eternal-Faith",
            "email": "2295616516@qq.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "\"登录\"",
                "parameters": [
                    {
                        "description": "user",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.UserLogin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登陆成功"
                    },
                    "400": {
                        "description": "输入格式错误"
                    },
                    "401": {
                        "description": "密码错误"
                    },
                    "404": {
                        "description": "用户不存在"
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "\"注册一个新用户\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "\"注册\"",
                "parameters": [
                    {
                        "description": "user",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.UserRegister"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "用户创建成功"
                    },
                    "400": {
                        "description": "输入有误，格式错误"
                    },
                    "401": {
                        "description": "电话号码重复"
                    }
                }
            }
        },
        "/broadcast/:broadcast_id": {
            "delete": {
                "description": "\"删除一个精彩放送的信息\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bro"
                ],
                "summary": "\"删除一个精彩放送信息\"",
                "parameters": [
                    {
                        "type": "string",
                        "description": "broadcast_id",
                        "name": "broadcast_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功"
                    },
                    "400": {
                        "description": "删除失败"
                    }
                }
            }
        },
        "/broadcast/avatar/:broadcast_id": {
            "post": {
                "description": "\"精彩放送图片\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bro"
                ],
                "summary": "\"修改精彩放送图片\"",
                "parameters": [
                    {
                        "type": "string",
                        "description": "broadcast_id",
                        "name": "broadcast_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "上传成功"
                    },
                    "400": {
                        "description": "上传失败"
                    },
                    "401": {
                        "description": "身份验证失败"
                    }
                }
            }
        },
        "/broadcast/basic_info": {
            "post": {
                "description": "\"添加精彩放送\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bro"
                ],
                "summary": "\"添加精彩放送信息\"",
                "parameters": [
                    {
                        "description": "broadcast",
                        "name": "broadcast",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Broadcast"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "上传成功"
                    },
                    "400": {
                        "description": "上传失败"
                    },
                    "401": {
                        "description": "身份验证失败"
                    }
                }
            }
        },
        "/broadcast/get_all": {
            "get": {
                "description": "\"精彩放送\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bro"
                ],
                "summary": "\"精彩放送\"",
                "parameters": [
                    {
                        "description": "Broadcast",
                        "name": "broadcast",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Broadcast"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "上传成功"
                    },
                    "400": {
                        "description": "上传失败"
                    },
                    "401": {
                        "description": "身份验证失败"
                    }
                }
            }
        },
        "/broadcast/get_single/:broadcast_id": {
            "get": {
                "description": "\"获取精彩放送详细信息\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bro"
                ],
                "summary": "\"获取单个精彩放送信息\"",
                "parameters": [
                    {
                        "type": "string",
                        "description": "broadcast_id",
                        "name": "broadcast_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功"
                    },
                    "400": {
                        "description": "获取失败"
                    },
                    "401": {
                        "description": "身份验证失败"
                    }
                }
            }
        },
        "/place/create": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "place"
                ],
                "summary": "\"创建地点信息\"",
                "parameters": [
                    {
                        "description": "地点",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/place.Places"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建成功"
                    },
                    "500": {
                        "description": "服务器错误"
                    }
                }
            }
        },
        "/place/pictureone": {
            "post": {
                "description": "\"修改地点图片1\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "place"
                ],
                "summary": "\"修改地点图片1\"",
                "parameters": [
                    {
                        "type": "file",
                        "description": "文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "id--地点的id",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"mgs\":\"success\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Script"
                        }
                    },
                    "400": {
                        "description": "上传失败,请检查token与其他配置参数是否正确"
                    }
                }
            }
        },
        "/place/picturethree": {
            "post": {
                "description": "\"修改地点图片2\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "place"
                ],
                "summary": "\"修改地点图片2\"",
                "parameters": [
                    {
                        "type": "file",
                        "description": "文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "id--地点的id",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"mgs\":\"success\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Script"
                        }
                    },
                    "400": {
                        "description": "上传失败,请检查token与其他配置参数是否正确"
                    }
                }
            }
        },
        "/place/picturetwo": {
            "post": {
                "description": "\"修改地点图片3\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "place"
                ],
                "summary": "\"修改地点图片3\"",
                "parameters": [
                    {
                        "type": "file",
                        "description": "文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "id--地点的id",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"mgs\":\"success\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Script"
                        }
                    },
                    "400": {
                        "description": "上传失败,请检查token与其他配置参数是否正确"
                    }
                }
            }
        },
        "/place/view": {
            "post": {
                "description": "\"查看地点信息\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "place"
                ],
                "summary": "\"查看地点\"",
                "parameters": [
                    {
                        "description": "地点名称",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/place.PlaceName"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Place"
                        }
                    },
                    "500": {
                        "description": "服务器错误"
                    }
                }
            }
        },
        "/script/cover": {
            "post": {
                "description": "\"修改剧本封面\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "script"
                ],
                "summary": "\"修改剧本封面\"",
                "parameters": [
                    {
                        "type": "file",
                        "description": "文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "id--剧本的id",
                        "name": "id",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"mgs\":\"success\"}",
                        "schema": {
                            "$ref": "#/definitions/model.Script"
                        }
                    },
                    "400": {
                        "description": "上传失败,请检查token与其他配置参数是否正确"
                    }
                }
            }
        },
        "/script/create": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "script"
                ],
                "summary": "\"创建剧本\"",
                "parameters": [
                    {
                        "description": "剧本",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/script.Scripts"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建成功"
                    },
                    "400": {
                        "description": "输入格式有误"
                    },
                    "500": {
                        "description": "服务器错误"
                    }
                }
            }
        },
        "/script/edit": {
            "post": {
                "description": "\"修改剧本内容\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "script"
                ],
                "summary": "\"修改剧本信息\"",
                "parameters": [
                    {
                        "description": "剧本",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/script.ScriptEditInfor"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "修改成功"
                    },
                    "400": {
                        "description": "输入格式有误"
                    },
                    "500": {
                        "description": "服务器错误"
                    }
                }
            }
        },
        "/script/interface": {
            "get": {
                "description": "\"返回所有剧本的封面、名字、ID\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "script"
                ],
                "summary": "\"剧本主界面\"",
                "responses": {
                    "200": {
                        "description": "获取成功",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Script"
                            }
                        }
                    },
                    "404": {
                        "description": "获取失败"
                    }
                }
            }
        },
        "/script/tag": {
            "post": {
                "description": "\"通过标签来进行分类\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "script"
                ],
                "summary": "\"剧本分类\"",
                "parameters": [
                    {
                        "description": "标签",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/script.Tag"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "搜索成功"
                    },
                    "400": {
                        "description": "输入格式有误"
                    },
                    "404": {
                        "description": "搜索失败"
                    },
                    "500": {
                        "description": "服务器错误"
                    }
                }
            }
        },
        "/script/view": {
            "post": {
                "description": "\"查看剧本的具体内容\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "script"
                ],
                "summary": "\"查看剧本\"",
                "parameters": [
                    {
                        "description": "剧本Id",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/script.ScriptId"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功"
                    },
                    "401": {
                        "description": "身份验证错误"
                    },
                    "500": {
                        "description": "服务器错误"
                    }
                }
            }
        },
        "/shop": {
            "post": {
                "description": "\"新增店铺信息\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shop"
                ],
                "summary": "\"店铺信息\"",
                "parameters": [
                    {
                        "description": "shop",
                        "name": "shop",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Shop"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "上传成功"
                    },
                    "400": {
                        "description": "上传失败"
                    },
                    "401": {
                        "description": "身份验证失败"
                    }
                }
            }
        },
        "/shop/:shop_id": {
            "delete": {
                "description": "\"删除一个店铺的信息\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shop"
                ],
                "summary": "\"删除店铺信息\"",
                "parameters": [
                    {
                        "type": "string",
                        "description": "shop_id",
                        "name": "shop_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功"
                    },
                    "400": {
                        "description": "删除失败"
                    }
                }
            }
        },
        "/shop/get_all": {
            "get": {
                "description": "\"获取商店详细信息\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shop"
                ],
                "summary": "\"商店信息\"",
                "parameters": [
                    {
                        "description": "shop",
                        "name": "shop",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Shop"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "上传成功"
                    },
                    "400": {
                        "description": "上传失败"
                    },
                    "401": {
                        "description": "身份验证失败"
                    }
                }
            }
        },
        "/shop/single_shop/:shop_id": {
            "get": {
                "description": "\"获取单个商店详细信息\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shop"
                ],
                "summary": "\"单个商店信息\"",
                "parameters": [
                    {
                        "type": "string",
                        "description": "shop_id",
                        "name": "shop_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取成功"
                    },
                    "400": {
                        "description": "获取失败"
                    },
                    "401": {
                        "description": "获取参数失败"
                    }
                }
            }
        },
        "/user/appointment": {
            "post": {
                "description": "\"预约时间，剧本id，剧本封面，预约状态\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "\"预约剧本\"",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "剧本Id",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.ScriptId"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "收藏成功"
                    },
                    "401": {
                        "description": "身份验证失败"
                    },
                    "500": {
                        "description": "服务器错误，收藏失败"
                    }
                }
            }
        },
        "/user/avatar": {
            "post": {
                "description": "\"修改用户头像\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "\"修改头像\"",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "上传成功"
                    },
                    "400": {
                        "description": "上传失败"
                    },
                    "401": {
                        "description": "身份验证失败"
                    }
                }
            }
        },
        "/user/cancel": {
            "post": {
                "description": "\"将收藏的剧本取消\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "\"取消收藏剧本\"",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "剧本Id",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.ScriptId"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "取消收藏成功"
                    },
                    "400": {
                        "description": "发送请求失败"
                    },
                    "401": {
                        "description": "身份验证失败"
                    },
                    "500": {
                        "description": "服务器错误，取消收藏收藏失败"
                    }
                }
            }
        },
        "/user/cancelappoint": {
            "post": {
                "description": "\"将预约的剧本取消\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "\"取消预约剧本\"",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "剧本Id",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.ScriptId"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "取消预约成功"
                    },
                    "400": {
                        "description": "发送请求失败"
                    },
                    "401": {
                        "description": "身份验证失败"
                    },
                    "500": {
                        "description": "服务器错误，取消收藏失败"
                    }
                }
            }
        },
        "/user/collection": {
            "post": {
                "description": "\"将该剧本收藏到我的收藏中\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "\"收藏剧本\"",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "剧本Id",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.ScriptId"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "收藏成功"
                    },
                    "401": {
                        "description": "身份验证失败"
                    },
                    "500": {
                        "description": "服务器错误，收藏失败"
                    }
                }
            }
        },
        "/user/edit": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "\"设置个人信息\"",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "user",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UserInfor"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登陆成功"
                    },
                    "400": {
                        "description": "输入格式错误"
                    },
                    "401": {
                        "description": "身份认证失效"
                    },
                    "404": {
                        "description": "用户不存在"
                    },
                    "500": {
                        "description": "服务器错误"
                    }
                }
            }
        },
        "/user/myappointment": {
            "get": {
                "description": "\"获取用户的所有剧本预约\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "\"我的预约(剧本)\"",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查看成功"
                    },
                    "400": {
                        "description": "发送请求失败"
                    },
                    "401": {
                        "description": "身份认证失效"
                    },
                    "500": {
                        "description": "服务器错误"
                    }
                }
            }
        },
        "/user/mycollection": {
            "get": {
                "description": "\"获取用户的所有剧本收藏\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "\"我的收藏(剧本)\"",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查看成功"
                    },
                    "400": {
                        "description": "发送请求失败"
                    },
                    "401": {
                        "description": "身份认证失效"
                    },
                    "500": {
                        "description": "服务器错误"
                    }
                }
            }
        },
        "/user/order": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "\"创建订单(剧本)\"",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "剧本Id",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.ScriptId"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建订单成功"
                    },
                    "400": {
                        "description": "输入格式有误"
                    },
                    "500": {
                        "description": "服务器错误"
                    }
                }
            }
        },
        "/user/payforscript": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "\"订单付款(剧本)\"",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "订单ID",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.OrderId"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "订单更新成功"
                    },
                    "400": {
                        "description": "输入格式错误"
                    },
                    "401": {
                        "description": "身份认证失效"
                    },
                    "500": {
                        "description": "服务器错误"
                    }
                }
            }
        },
        "/user/searchappointment": {
            "post": {
                "description": "\"通过标签来进行分类\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "\"剧本分类\"",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "预约状态",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.Status"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "搜索成功"
                    },
                    "400": {
                        "description": "输入格式有误"
                    },
                    "404": {
                        "description": "搜索失败"
                    },
                    "500": {
                        "description": "服务器错误"
                    }
                }
            }
        },
        "/user/updateappointmentstatus": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "\"更新预约状态\"",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "预约ID及状态",
                        "name": "object",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.Appointments"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "预约更新成功"
                    },
                    "400": {
                        "description": "输入格式错误"
                    },
                    "401": {
                        "description": "身份认证失效"
                    },
                    "500": {
                        "description": "服务器错误"
                    }
                }
            }
        },
        "/user/view": {
            "post": {
                "description": "\"获取用户的基本信息\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "\"游览个人信息\"",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "游览信息成功"
                    },
                    "401": {
                        "description": "身份验证失败"
                    },
                    "404": {
                        "description": "客户端错误"
                    }
                }
            }
        },
        "/user/vieworder": {
            "get": {
                "description": "\"查看所有订单(含时间，价格，剧本名字)\"",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "\"查看订单\"",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功"
                    },
                    "401": {
                        "description": "身份验证错误"
                    },
                    "500": {
                        "description": "服务器错误"
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.UserLogin": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "auth.UserRegister": {
            "type": "object",
            "properties": {
                "confirm_password": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "model.Broadcast": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "create_time": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "path": {
                    "type": "string"
                },
                "picture": {
                    "type": "string"
                },
                "sha": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "model.Place": {
            "type": "object",
            "properties": {
                "area": {
                    "description": "地点面积",
                    "type": "string"
                },
                "data": {
                    "description": "地点资料",
                    "type": "string"
                },
                "entertainment": {
                    "description": "娱乐项目数量",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "description": "地点名称",
                    "type": "string"
                },
                "path1": {
                    "type": "string"
                },
                "path2": {
                    "type": "string"
                },
                "path3": {
                    "type": "string"
                },
                "picture1": {
                    "description": "地点轮换封面1",
                    "type": "string"
                },
                "picture2": {
                    "description": "地点轮换封面2",
                    "type": "string"
                },
                "picture3": {
                    "description": "地点轮换封面3",
                    "type": "string"
                },
                "scenic_spot": {
                    "description": "特色景点数量",
                    "type": "string"
                },
                "sha1": {
                    "type": "string"
                },
                "sha2": {
                    "type": "string"
                },
                "sha3": {
                    "type": "string"
                },
                "visitor": {
                    "description": "最大游客量",
                    "type": "string"
                }
            }
        },
        "model.Script": {
            "type": "object",
            "properties": {
                "avatar": {
                    "description": "剧本封面",
                    "type": "string"
                },
                "brief_intro": {
                    "description": "剧本简介",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "introduction": {
                    "description": "剧本介绍",
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "place": {
                    "description": "地点",
                    "type": "string"
                },
                "price": {
                    "description": "价格",
                    "type": "integer"
                },
                "script_name": {
                    "description": "剧本名称",
                    "type": "string"
                },
                "sha": {
                    "type": "string"
                },
                "tag1": {
                    "description": "标签一",
                    "type": "string"
                },
                "tag2": {
                    "description": "标签二",
                    "type": "string"
                },
                "tag3": {
                    "description": "标签三",
                    "type": "string"
                },
                "tag4": {
                    "description": "标签四",
                    "type": "string"
                },
                "tag5": {
                    "description": "标签五",
                    "type": "string"
                },
                "time": {
                    "description": "剧本时长",
                    "type": "string"
                }
            }
        },
        "model.Shop": {
            "type": "object",
            "properties": {
                "current_num": {
                    "type": "string"
                },
                "fiery_num": {
                    "description": "火热指数",
                    "type": "string"
                },
                "hot_line": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "opening_time": {
                    "description": "营业时间",
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "picture": {
                    "description": "商店图片",
                    "type": "string"
                },
                "service_intro": {
                    "description": "服务介绍",
                    "type": "string"
                },
                "sha": {
                    "type": "string"
                },
                "shop_name": {
                    "description": "商店名称",
                    "type": "string"
                },
                "should_know": {
                    "description": "需知",
                    "type": "string"
                },
                "vip_service": {
                    "description": "vip服务",
                    "type": "string"
                }
            }
        },
        "place.PlaceName": {
            "type": "object",
            "properties": {
                "place_name": {
                    "description": "地点名称",
                    "type": "string"
                }
            }
        },
        "place.Places": {
            "type": "object",
            "properties": {
                "area": {
                    "description": "地点面积",
                    "type": "string"
                },
                "data": {
                    "description": "地点资料",
                    "type": "string"
                },
                "entertainment": {
                    "description": "娱乐项目数量",
                    "type": "string"
                },
                "name": {
                    "description": "地点名称",
                    "type": "string"
                },
                "scenic_spot": {
                    "description": "特色景点数量",
                    "type": "string"
                },
                "visitor": {
                    "description": "最大游客量",
                    "type": "string"
                }
            }
        },
        "script.ScriptEditInfor": {
            "type": "object",
            "properties": {
                "brief_intro": {
                    "description": "剧本简介",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "introduction": {
                    "description": "剧本介绍",
                    "type": "string"
                },
                "place": {
                    "description": "地点",
                    "type": "string"
                },
                "price": {
                    "description": "价格",
                    "type": "integer"
                },
                "script_name": {
                    "description": "剧本名称",
                    "type": "string"
                },
                "tag1": {
                    "description": "标签一",
                    "type": "string"
                },
                "tag2": {
                    "description": "标签二",
                    "type": "string"
                },
                "tag3": {
                    "description": "标签三",
                    "type": "string"
                },
                "tag4": {
                    "description": "标签四",
                    "type": "string"
                },
                "tag5": {
                    "description": "标签五",
                    "type": "string"
                },
                "time": {
                    "description": "剧本时间",
                    "type": "string"
                }
            }
        },
        "script.ScriptId": {
            "type": "object",
            "properties": {
                "script_id": {
                    "description": "剧本的ID",
                    "type": "string"
                }
            }
        },
        "script.Scripts": {
            "type": "object",
            "properties": {
                "brief_intro": {
                    "description": "剧本简介",
                    "type": "string"
                },
                "introduction": {
                    "description": "剧本介绍",
                    "type": "string"
                },
                "place": {
                    "description": "地点",
                    "type": "string"
                },
                "price": {
                    "description": "价格",
                    "type": "integer"
                },
                "script_name": {
                    "description": "剧本名称",
                    "type": "string"
                },
                "tag1": {
                    "description": "标签一",
                    "type": "string"
                },
                "tag2": {
                    "description": "标签二",
                    "type": "string"
                },
                "tag3": {
                    "description": "标签三",
                    "type": "string"
                },
                "tag4": {
                    "description": "标签四",
                    "type": "string"
                },
                "tag5": {
                    "description": "标签五",
                    "type": "string"
                },
                "time": {
                    "description": "剧本时间",
                    "type": "string"
                }
            }
        },
        "script.Tag": {
            "type": "object",
            "properties": {
                "tag": {
                    "description": "标签",
                    "type": "string"
                }
            }
        },
        "user.Appointments": {
            "type": "object",
            "properties": {
                "appointment_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "user.OrderId": {
            "type": "object",
            "properties": {
                "order_id": {
                    "type": "integer"
                }
            }
        },
        "user.ScriptId": {
            "type": "object",
            "properties": {
                "script_id": {
                    "description": "剧本的ID",
                    "type": "string"
                }
            }
        },
        "user.Status": {
            "type": "object",
            "properties": {
                "status": {
                    "description": "标签",
                    "type": "string"
                }
            }
        },
        "user.UserInfor": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "gender": {
                    "description": "性别",
                    "type": "string"
                },
                "idcard": {
                    "description": "身份证号",
                    "type": "string"
                },
                "nickname": {
                    "description": "用户名",
                    "type": "string"
                },
                "phone": {
                    "description": "电话号码",
                    "type": "string"
                },
                "realname": {
                    "description": "真实姓名",
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0.0",
	Host:        "localhost:8918",
	BasePath:    "",
	Schemes:     []string{"http"},
	Title:       "uima",
	Description: "山乡剧变",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
